/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import metier.CategorieProduit;
import metier.Produit;
import metier.SousCategorieArtEtCulture;
import metier.SousCategorieBDEtManga;
import metier.SousCategorieJeunesse;
import metier.SousCategorieLitterature;

/**
 *
 * @author pc
 */
public class FenAcceuil extends javax.swing.JFrame {

    /**
     * Creates new form FenAcceuil
     */
    private static List<Produit> lesProduits;

    private ComboBoxModel<String> modeleDesCategories;
    private ComboBoxModel<String> modeleDesSousCategories;
    private List<Produit> lesProduitsTrouves;
    public static String HOST = "jdbc:mysql://localhost:3306/tp33?zeroDateTimeBehavior=convertToNull"; //jdbc:mysql://localhost:3306/tp33?zeroDateTimeBehavior=convertToNull [root on Default schema]
    public static String USERNAME = "root";
    public static String PASSWORD = "";//"root"

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    public FenAcceuil() {

        //initialisation des catégories --> a modifier pour aller recup infos dans bdd --> remplacer les valeurs
        //que prend tabCategories par les données de la BDD ?
        Object[] tabCategories = CategorieProduit.getLesCategoriesProduit().toArray();
        modeleDesCategories = new DefaultComboBoxModel(tabCategories);

        // implémentation avec Master / Detail
        modeleDesSousCategories = new DefaultComboBoxModel<String>();
        lesProduitsTrouves = new ArrayList<>();

        initComponents();
//        selectProduit();

        // Création de quelques produits en dur
        /* public Produit(String titre, CategorieProduit categorie, String description,
            Double prix, int quantite, int seui)*/
       /* Produit p1 = new Produit("Berserk",
                CategorieProduit.B, "seinen bien",
                10.52, 207, 15);
        Produit p2 = new Produit("Vagabond",
                CategorieProduit.B, "seinen bien",
                7.0, 58, 10);
        Produit p3 = new Produit("Sapiens",
                CategorieProduit.A, "japprend dtrucs",
                10.52, 207, 15);*/

        lesProduits = Produit.getListeDesProduits();

        Collections.sort(lesProduits);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpan_accueil = new javax.swing.JTabbedPane();
        pan_produits = new javax.swing.JPanel();
        pan_rechercheProduits = new javax.swing.JPanel();
        lbl_titre = new javax.swing.JLabel();
        lbl_categories = new javax.swing.JLabel();
        cb_categories = new javax.swing.JComboBox<>();
        cb_sousCategories = new javax.swing.JComboBox<>();
        tf_titre = new javax.swing.JTextField();
        btn_effacer = new javax.swing.JButton();
        btn_rechercher = new javax.swing.JButton();
        pan_affichage = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        lbl_sousCatAff = new javax.swing.JLabel();
        lbl_editeur = new javax.swing.JLabel();
        lbl_catAff = new javax.swing.JLabel();
        cb_categoriesAff = new javax.swing.JComboBox<>();
        cb_sousCategoriesAff = new javax.swing.JComboBox<>();
        tf_id = new javax.swing.JTextField();
        tf_titreAff = new javax.swing.JTextField();
        lbl_titreAff1 = new javax.swing.JLabel();
        lbl_auteur = new javax.swing.JLabel();
        lbl_anneEdition = new javax.swing.JLabel();
        tf_editeurAff = new javax.swing.JTextField();
        tf_auteurAff = new javax.swing.JTextField();
        tf_anneeEditionAff = new javax.swing.JTextField();
        pan_modif = new javax.swing.JPanel();
        lbl_resume = new javax.swing.JLabel();
        lbl_prix = new javax.swing.JLabel();
        lbl_enPromo = new javax.swing.JLabel();
        lbl_prixReduit = new javax.swing.JLabel();
        lbl_seuil = new javax.swing.JLabel();
        tf_resume = new javax.swing.JTextField();
        tf_prixReduit = new javax.swing.JTextField();
        tf_prix = new javax.swing.JTextField();
        tf_enPromo = new javax.swing.JTextField();
        tf_seuil = new javax.swing.JTextField();
        lbl_stock = new javax.swing.JLabel();
        tf_stock = new javax.swing.JTextField();
        btn_ajouter = new javax.swing.JButton();
        btn_modif = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_modif1 = new javax.swing.JButton();
        pan_categories = new javax.swing.JPanel();
        panGestionCategorie = new javax.swing.JPanel();
        lbl_categorie4 = new javax.swing.JLabel();
        lbl_sousCategorie4 = new javax.swing.JLabel();
        lbl_newCategorie2 = new javax.swing.JLabel();
        tf_newCategorie2 = new javax.swing.JTextField();
        cbb_categorieGestion = new javax.swing.JComboBox<>();
        cbb_sousCategorieGestion = new javax.swing.JComboBox<>();
        bt_supprimerCategorie2 = new javax.swing.JButton();
        bt_ajouterSousCatégorie2 = new javax.swing.JButton();
        lbl_newSousCategorie2 = new javax.swing.JLabel();
        tf_newSousCategorie2 = new javax.swing.JTextField();
        bt_ajouterCatégorie2 = new javax.swing.JButton();
        bt_supprimerSousCategorie2 = new javax.swing.JButton();
        bt_cate_valider = new javax.swing.JButton();
        pan_promotions = new javax.swing.JPanel();
        pan_clients = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_pwd = new javax.swing.JLabel();
        tf_pwd = new javax.swing.JPasswordField();
        lbl_login = new javax.swing.JLabel();
        tf_login = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mb_menu = new javax.swing.JMenuBar();
        m_fichier = new javax.swing.JMenu();
        mi_categories = new javax.swing.JMenuItem();
        mi_promotions = new javax.swing.JMenuItem();
        mi_clients = new javax.swing.JMenuItem();
        mi_charger = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mi_sauvegarder = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mi_quitter = new javax.swing.JMenuItem();
        m_aPropos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JIYU - Application de gestion de stock");

        pan_produits.setPreferredSize(new java.awt.Dimension(1200, 7));

        pan_rechercheProduits.setBorder(javax.swing.BorderFactory.createTitledBorder("Rechercher un produit"));

        lbl_titre.setText("Titre :");

        lbl_categories.setText("Catégories :");

        cb_categories.setModel(modeleDesCategories);
        cb_categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoriesActionPerformed(evt);
            }
        });

        cb_sousCategories.setModel(modeleDesSousCategories);
        cb_sousCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sousCategoriesActionPerformed(evt);
            }
        });

        btn_effacer.setText("Effacer");
        btn_effacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_effacerMouseClicked(evt);
            }
        });
        btn_effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_effacerActionPerformed(evt);
            }
        });

        btn_rechercher.setText("Rechercher");
        btn_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_rechercheProduitsLayout = new javax.swing.GroupLayout(pan_rechercheProduits);
        pan_rechercheProduits.setLayout(pan_rechercheProduitsLayout);
        pan_rechercheProduitsLayout.setHorizontalGroup(
            pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_rechercheProduitsLayout.createSequentialGroup()
                .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_rechercheProduitsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_effacer)
                        .addGap(18, 18, 18)
                        .addComponent(btn_rechercher))
                    .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pan_rechercheProduitsLayout.createSequentialGroup()
                            .addComponent(lbl_categories, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_categories, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(cb_sousCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pan_rechercheProduitsLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(lbl_titre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pan_rechercheProduitsLayout.setVerticalGroup(
            pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_rechercheProduitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titre)
                    .addComponent(tf_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_categories)
                    .addComponent(cb_categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_sousCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_effacer)
                    .addComponent(btn_rechercher)))
        );

        pan_affichage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pan_affichage.setPreferredSize(new java.awt.Dimension(1088, 99));

        lbl_id.setText("ID :");

        lbl_sousCatAff.setText("Sous-catégorie :");

        lbl_editeur.setText("Editeur :");

        lbl_catAff.setText("Catégorie :");

        cb_categoriesAff.setModel(modeleDesCategories);
        cb_categoriesAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoriesAffActionPerformed(evt);
            }
        });

        cb_sousCategoriesAff.setModel(modeleDesSousCategories);

        tf_id.setEditable(false);
        tf_id.setBackground(new java.awt.Color(204, 204, 204));
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        tf_titreAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_titreAffActionPerformed(evt);
            }
        });

        lbl_titreAff1.setText("Titre :");

        lbl_auteur.setText("Auteur :");

        lbl_anneEdition.setText("Année edition :");

        tf_editeurAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_editeurAffActionPerformed(evt);
            }
        });

        tf_auteurAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_auteurAffActionPerformed(evt);
            }
        });

        tf_anneeEditionAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_anneeEditionAffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_affichageLayout = new javax.swing.GroupLayout(pan_affichage);
        pan_affichage.setLayout(pan_affichageLayout);
        pan_affichageLayout.setHorizontalGroup(
            pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_affichageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_id)
                    .addComponent(lbl_titreAff1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_affichageLayout.createSequentialGroup()
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_catAff, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_titreAff, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_affichageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_categoriesAff, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(lbl_sousCatAff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_sousCategoriesAff, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(pan_affichageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_auteurAff, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_editeur, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_editeurAff, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_anneEdition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_anneeEditionAff, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        pan_affichageLayout.setVerticalGroup(
            pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_affichageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id)
                    .addComponent(lbl_catAff)
                    .addComponent(cb_categoriesAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sousCatAff)
                    .addComponent(cb_sousCategoriesAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titreAff1)
                    .addComponent(tf_titreAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_auteur)
                    .addComponent(tf_auteurAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_editeur)
                    .addComponent(tf_editeurAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_anneeEditionAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_anneEdition))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_modif.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pan_modif.setPreferredSize(new java.awt.Dimension(1088, 251));

        lbl_resume.setText("Résumé :");

        lbl_prix.setText("Prix :");

        lbl_enPromo.setText("En promotion ? :");

        lbl_prixReduit.setText("Prix réduit :");

        lbl_seuil.setText("Seuil alerte :");

        tf_prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_prixActionPerformed(evt);
            }
        });

        lbl_stock.setText("Quantité en stock :");

        javax.swing.GroupLayout pan_modifLayout = new javax.swing.GroupLayout(pan_modif);
        pan_modif.setLayout(pan_modifLayout);
        pan_modifLayout.setHorizontalGroup(
            pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_modifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_resume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_modifLayout.createSequentialGroup()
                        .addComponent(lbl_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_prixReduit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_prixReduit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_enPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_enPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_seuil, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_seuil, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_resume))
                .addContainerGap())
        );
        pan_modifLayout.setVerticalGroup(
            pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_modifLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_resume, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_resume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_seuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_prix)
                        .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_enPromo)
                        .addComponent(tf_enPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_stock)
                        .addComponent(tf_prixReduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_prixReduit)
                        .addComponent(lbl_seuil)))
                .addContainerGap())
        );

        btn_ajouter.setText("Ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });

        btn_modif.setText("Modifier");
        btn_modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifActionPerformed(evt);
            }
        });

        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modif1.setBackground(new java.awt.Color(255, 204, 204));
        btn_modif1.setText("Suivant");
        btn_modif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modif1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_produitsLayout = new javax.swing.GroupLayout(pan_produits);
        pan_produits.setLayout(pan_produitsLayout);
        pan_produitsLayout.setHorizontalGroup(
            pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_produitsLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(pan_rechercheProduits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pan_produitsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_produitsLayout.createSequentialGroup()
                        .addComponent(btn_supprimer)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btn_modif1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pan_modif, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
                        .addComponent(pan_affichage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_produitsLayout.setVerticalGroup(
            pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_produitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pan_rechercheProduits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_affichage, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pan_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_supprimer)
                    .addComponent(btn_ajouter)
                    .addComponent(btn_modif)
                    .addComponent(btn_modif1))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        tpan_accueil.addTab("Produits", pan_produits);

        panGestionCategorie.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion des Catégories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 10))); // NOI18N

        lbl_categorie4.setText("Liste des catégories");

        lbl_sousCategorie4.setText("Sous-catégories associées");

        lbl_newCategorie2.setText("Nouvelle Catégorie :");

        cbb_categorieGestion.setModel(modeleDesCategories);
        cbb_categorieGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_categorieGestionActionPerformed(evt);
            }
        });

        cbb_sousCategorieGestion.setModel(modeleDesSousCategories);

        bt_supprimerCategorie2.setText("Supprimer la catégorie");
        bt_supprimerCategorie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimerCategorie2ActionPerformed(evt);
            }
        });

        bt_ajouterSousCatégorie2.setText("Ajouter la sous-catégorie");

        lbl_newSousCategorie2.setText("Nouvelle Sous-Catégorie :");

        bt_ajouterCatégorie2.setText("Ajouter la catégorie");

        bt_supprimerSousCategorie2.setText("Supprimer la sous-catégorie");

        javax.swing.GroupLayout panGestionCategorieLayout = new javax.swing.GroupLayout(panGestionCategorie);
        panGestionCategorie.setLayout(panGestionCategorieLayout);
        panGestionCategorieLayout.setHorizontalGroup(
            panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGestionCategorieLayout.createSequentialGroup()
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panGestionCategorieLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lbl_newCategorie2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_newCategorie2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panGestionCategorieLayout.createSequentialGroup()
                            .addComponent(lbl_categorie4)
                            .addGap(1, 1, 1)
                            .addComponent(cbb_categorieGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panGestionCategorieLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_ajouterCatégorie2)
                            .addComponent(bt_supprimerCategorie2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panGestionCategorieLayout.createSequentialGroup()
                            .addComponent(lbl_newSousCategorie2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_newSousCategorie2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panGestionCategorieLayout.createSequentialGroup()
                            .addComponent(lbl_sousCategorie4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbb_sousCategorieGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_ajouterSousCatégorie2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_supprimerSousCategorie2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panGestionCategorieLayout.setVerticalGroup(
            panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGestionCategorieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_categorie4)
                    .addComponent(cbb_categorieGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_sousCategorieGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sousCategorie4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_supprimerCategorie2)
                    .addComponent(bt_supprimerSousCategorie2))
                .addGap(18, 18, 18)
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_newSousCategorie2)
                    .addComponent(tf_newSousCategorie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_newCategorie2)
                    .addComponent(tf_newCategorie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ajouterSousCatégorie2)
                    .addComponent(bt_ajouterCatégorie2))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        bt_cate_valider.setText("Valider");
        bt_cate_valider.setToolTipText("Sauvegarder les données sur les catégories");
        bt_cate_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cate_validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_categoriesLayout = new javax.swing.GroupLayout(pan_categories);
        pan_categories.setLayout(pan_categoriesLayout);
        pan_categoriesLayout.setHorizontalGroup(
            pan_categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_categoriesLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(panGestionCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_categoriesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_cate_valider)
                .addGap(229, 229, 229))
        );
        pan_categoriesLayout.setVerticalGroup(
            pan_categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_categoriesLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(panGestionCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_cate_valider)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        tpan_accueil.addTab("Catégories", pan_categories);

        javax.swing.GroupLayout pan_promotionsLayout = new javax.swing.GroupLayout(pan_promotions);
        pan_promotions.setLayout(pan_promotionsLayout);
        pan_promotionsLayout.setHorizontalGroup(
            pan_promotionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        pan_promotionsLayout.setVerticalGroup(
            pan_promotionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        tpan_accueil.addTab("Promotions", pan_promotions);

        lbl_pwd.setText("Mot de passe :");

        tf_pwd.setText("jPasswordField1");

        lbl_login.setText("Login :");

        tf_login.setText("                      ");

        jLabel1.setText("(IHM à finir avec une JTable au TP4)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_pwd)
                        .addGap(26, 26, 26)
                        .addComponent(tf_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_login))
                        .addGap(18, 18, 18)
                        .addComponent(tf_login, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_login)
                    .addComponent(tf_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pwd)
                    .addComponent(tf_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout pan_clientsLayout = new javax.swing.GroupLayout(pan_clients);
        pan_clients.setLayout(pan_clientsLayout);
        pan_clientsLayout.setHorizontalGroup(
            pan_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_clientsLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        pan_clientsLayout.setVerticalGroup(
            pan_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_clientsLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        tpan_accueil.addTab("Clients", pan_clients);

        getContentPane().add(tpan_accueil, java.awt.BorderLayout.PAGE_START);

        m_fichier.setText("Fichier");
        m_fichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_fichierActionPerformed(evt);
            }
        });

        mi_categories.setText("Gestion Catégories");
        mi_categories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_categoriesMouseClicked(evt);
            }
        });
        mi_categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_categoriesActionPerformed(evt);
            }
        });
        m_fichier.add(mi_categories);

        mi_promotions.setText("Gestion Promotions");
        mi_promotions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_promotionsMouseClicked(evt);
            }
        });
        mi_promotions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_promotionsActionPerformed(evt);
            }
        });
        m_fichier.add(mi_promotions);

        mi_clients.setText("Gestion Clients");
        mi_clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_clientsMouseClicked(evt);
            }
        });
        mi_clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_clientsActionPerformed(evt);
            }
        });
        m_fichier.add(mi_clients);

        mi_charger.setText("Charger");
        mi_charger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_chargerActionPerformed(evt);
            }
        });
        m_fichier.add(mi_charger);
        m_fichier.add(jSeparator1);

        mi_sauvegarder.setText("Sauvegarder");
        mi_sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_sauvegarderActionPerformed(evt);
            }
        });
        m_fichier.add(mi_sauvegarder);
        m_fichier.add(jSeparator2);

        mi_quitter.setText("Quitter");
        mi_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_quitterActionPerformed(evt);
            }
        });
        m_fichier.add(mi_quitter);

        mb_menu.add(m_fichier);

        m_aPropos.setText("A propos");

        jMenuItem1.setText("Version");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        m_aPropos.add(jMenuItem1);

        mb_menu.add(m_aPropos);

        setJMenuBar(mb_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_categoriesActionPerformed
        // TODO add your handling code here:
        tpan_accueil.setSelectedComponent(pan_categories);
    }//GEN-LAST:event_mi_categoriesActionPerformed
    private void affecterDetailCBBox(String ch, JComboBox cbb) {
        // cette méthode affecte la bonne liste de sous-catégories à la CBBox
        Object[] tabCategories;
        boolean flagErreurSousCategorie = false;

        CategorieProduit cat = CategorieProduit.getCategorieFromString(ch);

        switch (cat) {
            case L:
                tabCategories = SousCategorieLitterature.getLesSousCategoriesLitterature().toArray();//select nom_sous_cat from sous_categorie
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                // cbBoxSousCategorieModele = new DefaultComboBoxModel(SousCategorieAccessoires.values());
                // (renvoie les VALEURS de l'énumeration)
                break;
            case J:
                tabCategories = SousCategorieJeunesse.getLesSousCategoriesJeunesse().toArray();
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                break;
            case B:
                tabCategories = SousCategorieBDEtManga.getLesSousCategoriesBDEtManga().toArray();
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                break;
            case A:
                tabCategories = SousCategorieArtEtCulture.getLesSousCategoriesArtEtCulture().toArray();
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                break;
            default:
                flagErreurSousCategorie = true;
                tabCategories = new Object[]{"", "", "", ""};
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                break;
        }
        cbb.setModel(modeleDesSousCategories);

        if (!flagErreurSousCategorie) {
            cbb.setVisible(true);
        } else {
            cbb.setVisible(false);
        }
    }

    private void ajouterProduit() {
        try {

            con = DriverManager.getConnection(HOST, USERNAME, PASSWORD);
            PreparedStatement add = con.prepareStatement("insert into PRODUIT(titre, prix, resumé, auteur, editeur"
                    + ",anne_edition, prix_reduit, stock, seuil) values (?,?,?,?,?,?,?,?,?)");

            add.setString(1, tf_titreAff.getText());
            add.setDouble(2, Double.valueOf(tf_prix.getText()));
            add.setString(3, tf_resume.getText());
            add.setString(4, tf_auteurAff.getText());
            add.setString(5, tf_editeurAff.getText());
            add.setInt(6,Integer.valueOf(tf_anneeEditionAff.getText()));          
            add.setDouble(7,Double.valueOf(tf_prixReduit.getText()));
            add.setInt(8,Integer.valueOf(tf_stock.getText()));
            //add.setInt(9,Integer.valueOf(tf_enPromo.getText()));
            add.setInt(9,Integer.valueOf(tf_seuil.getText())); 
            //add.setInt(10,Integer.valueOf(tf_enStock.getText()));
            
            
            
            //add.setString(11,cb_categoriesAff.getSelectedItem().toString()); // a voir
            //add.setString(12,cb_sousCategoriesAff.getSelectedItem().toString());//a voir
            
            add.execute();
            JOptionPane.showMessageDialog(this, "Le produit a bien été ajouté !");

            //.close();
            // selectProduit();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    private void supprimerProduit() {
        try {
            con = DriverManager.getConnection(HOST, USERNAME, PASSWORD);
            String id = tf_id.getText();
            String query = "Delete from PRODUIT where id_produit=" + id;
            Statement supp = con.createStatement();
            supp.executeUpdate(query);
            // selectProduit();
            JOptionPane.showMessageDialog(this, "Le produit a bien été supprimé !");
            //Produit.setCpt(Produit.getCpt() - 1);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void modifierProduit() {
        try {
            con = DriverManager.getConnection(HOST, USERNAME, PASSWORD);
            //problèmes avec type de annee_edition, prixreduit(tauxreduction),stock, categories et boolen --> comment recup ? types doivent etre equivalent ? convertion ? 
            String updateQuery = "UPDATE produit p INNER JOIN categorie c ON p.id_categorie=c.id_categorie "
                    + "INNER JOIN sous_categorie s ON c.id_categorie=s.id_categorie SET titre='" + tf_titreAff.getText() + "'" + ",auteur='" 
                    + tf_auteurAff.getText() + "'" + ",editeur='" + tf_editeurAff.getText() + "'" 
                    + ",resumé='" + tf_resume.getText() + "'" + ",prix='" + tf_prix.getText() +"'"
                    +",annee_edition='"+tf_anneeEditionAff.getText()+"'"+"prix_reduit:'"+tf_prixReduit+"'"
                    +",stock='"+tf_stock.getText()+"'"+",en_promo='"+tf_enPromo.getText()+"'"
                    +",seuil='"+tf_seuil.getText()+"'"+",nom_categorie='"+cb_categoriesAff.getSelectedItem().toString() +"'"
                    +",sousCategorieNom='"+cb_sousCategoriesAff.getSelectedItem().toString()+"'"+ " WHERE id_produit=" + tf_id.getText();
                    
            PreparedStatement add = con.prepareStatement(updateQuery);
            add.execute();
            JOptionPane.showMessageDialog(this, "Le produit a bien été modifié !");
            // selectProduit();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
    private void mi_clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_clientsActionPerformed
        // TODO add your handling code here:
        tpan_accueil.setSelectedComponent(pan_clients);
    }//GEN-LAST:event_mi_clientsActionPerformed

    private void mi_sauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_sauvegarderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_sauvegarderActionPerformed

    private void mi_promotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_promotionsActionPerformed
        // TODO add your handling code here:
        tpan_accueil.setSelectedComponent(pan_promotions);
    }//GEN-LAST:event_mi_promotionsActionPerformed

    private void mi_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_quitterActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment quitter ?", "Attention", JOptionPane.OK_CANCEL_OPTION);
        if (reply == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mi_quitterActionPerformed

    private void mi_chargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_chargerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_chargerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Application réalisée par Romane BERTHE et Marie MICHEL - Version 1",
                "A propos...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mi_categoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_categoriesMouseClicked


    }//GEN-LAST:event_mi_categoriesMouseClicked

    private void mi_promotionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_promotionsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_promotionsMouseClicked

    private void mi_clientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_clientsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_clientsMouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void m_fichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_fichierActionPerformed
        // TODO add your handling code here:
        tpan_accueil.setSelectedComponent(pan_categories);
    }//GEN-LAST:event_m_fichierActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        // TODO add your handling code here:
        if (tf_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez selectionner un produit à supprimer.");
        } else {
            supprimerProduit();

        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifActionPerformed
        // TODO add your handling code here:
        /*if (tf_titreAff.getText().isEmpty() || tf_auteurAff.getText().isEmpty() || tf_editeurAff.getText().isEmpty() || tf_anneeEditionAff.getText().isEmpty() || tf_resume.getText().isEmpty() || tf_prix.getText().isEmpty() || tf_prixReduit.getText().isEmpty() || tf_enPromo.getText().isEmpty() || tf_stock.getText().isEmpty() || cb_categoriesAff.getSelectedItem().toString().isEmpty() || cb_sousCategoriesAff.getSelectedItem().toString().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Il manque des informations.");

        }//voir avec la classe cb_connexion --> methode d'execution des requêtes
         else
        {*/
        modifierProduit();


    }//GEN-LAST:event_btn_modifActionPerformed

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // TODO add your handling code here:
        ajouterProduit();
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void tf_anneeEditionAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_anneeEditionAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_anneeEditionAffActionPerformed

    private void tf_auteurAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_auteurAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_auteurAffActionPerformed

    private void tf_editeurAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_editeurAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_editeurAffActionPerformed

    private void tf_titreAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_titreAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_titreAffActionPerformed

    private void tf_prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_prixActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_tf_idActionPerformed

    private void cb_categoriesAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoriesAffActionPerformed
        // TODO add your handling code here:
        String laCategorie = (String) cb_categoriesAff.getSelectedItem();
        this.affecterDetailCBBox(laCategorie, cb_sousCategoriesAff);
    }//GEN-LAST:event_cb_categoriesAffActionPerformed

    private void cbb_categorieGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_categorieGestionActionPerformed
        String laCategorie = (String) cbb_categorieGestion.getSelectedItem();
        this.affecterDetailCBBox(laCategorie, cbb_sousCategorieGestion);
    }//GEN-LAST:event_cbb_categorieGestionActionPerformed

    private void bt_supprimerCategorie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimerCategorie2ActionPerformed
        // attention : on ne pourra supprimer la catégorie que s'il n'y a plus
        // aucun produit de cette catégorie
        // idée : afficher la liste des produits concernés

    }//GEN-LAST:event_bt_supprimerCategorie2ActionPerformed

    private void bt_cate_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cate_validerActionPerformed
        // sauvegarder les catégories et sous-catégories avec les modifs effectuées
    }//GEN-LAST:event_bt_cate_validerActionPerformed

    private void btn_modif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modif1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modif1ActionPerformed

    private void btn_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rechercherActionPerformed
        // TODO add your handling code here:
        //rajouter un message si le produit rechercher n'existe pas + eviter casse/MAJUSCULE
        try {

            con = DriverManager.getConnection(HOST, USERNAME, PASSWORD);
            Statement stat = con.createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM produit INNER JOIN categorie c "
                    + "ON c.id_categorie = produit.id_categorie INNER JOIN sous_categorie s "
                    + "ON s.id_sous_categorie = produit.id_sous_categorie WHERE titre='" + tf_titre.getText() + "'");//

            while (result.next()) {
                tf_id.setText(result.getString("id_produit")); //attention ID = int, peut etre cast
                tf_titreAff.setText(result.getString("titre"));
                tf_prix.setText(result.getString("prix"));
                tf_resume.setText(result.getString("resumé"));
                tf_auteurAff.setText(result.getString("auteur"));
                tf_editeurAff.setText(result.getString("editeur"));
                tf_stock.setText(result.getString("stock"));
                tf_anneeEditionAff.setText(result.getString("anne_edition"));
                tf_prixReduit.setText(result.getString("prix_reduit"));

                tf_enPromo.setText(result.getString("en_promotion"));
                tf_seuil.setText(result.getString("seuil"));// A RAJOUTER BDD
                //comment faire pour cat sous cat --> pas la même table
                cb_categoriesAff.setSelectedItem(result.getString("nom_categorie"));
                //cb_categoriesAff.setSelectedItem(cb_categories.getSelectedItem());
                cb_sousCategoriesAff.setSelectedItem(result.getString("nom_sous_cat"));

            }

            con.close();

            //selectProduit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_rechercherActionPerformed

    private void btn_effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_effacerActionPerformed
        // TODO add your handling code here:
        tf_titre.setText("");
        cb_categories.setSelectedIndex(0);
        cb_sousCategories.setSelectedIndex(0);
        //cb_sousCategories.removeAllItems();
        cb_sousCategoriesAff.removeAllItems();
        cb_categoriesAff.removeAllItems();
        tf_id.setText("");
        tf_titreAff.setText("");
        tf_auteurAff.setText("");
        tf_editeurAff.setText("");
        tf_anneeEditionAff.setText("");
        tf_resume.setText("");
        tf_prix.setText("");
        tf_prixReduit.setText("");
        tf_enPromo.setText("");
        tf_seuil.setText("");
        tf_stock.setText("");
    }//GEN-LAST:event_btn_effacerActionPerformed

    private void btn_effacerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_effacerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_effacerMouseClicked

    private void cb_sousCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sousCategoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_sousCategoriesActionPerformed

    private void cb_categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoriesActionPerformed
        // TODO add your handling code here:
        // on définit le contenu de la comboBox des sous categories en
        // fonction de l'item selectionné
        String laCategorie = (String) cb_categories.getSelectedItem(); // getSelectedItem() renvoie un Object par defaut
        this.affecterDetailCBBox(laCategorie, cb_sousCategories);

    }//GEN-LAST:event_cb_categoriesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ajouterCatégorie2;
    private javax.swing.JButton bt_ajouterSousCatégorie2;
    private javax.swing.JButton bt_cate_valider;
    private javax.swing.JButton bt_supprimerCategorie2;
    private javax.swing.JButton bt_supprimerSousCategorie2;
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_effacer;
    private javax.swing.JButton btn_modif;
    private javax.swing.JButton btn_modif1;
    private javax.swing.JButton btn_rechercher;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JComboBox<String> cb_categories;
    private javax.swing.JComboBox<String> cb_categoriesAff;
    private javax.swing.JComboBox<String> cb_sousCategories;
    private javax.swing.JComboBox<String> cb_sousCategoriesAff;
    private javax.swing.JComboBox<String> cbb_categorieGestion;
    private javax.swing.JComboBox<String> cbb_sousCategorieGestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbl_anneEdition;
    private javax.swing.JLabel lbl_auteur;
    private javax.swing.JLabel lbl_catAff;
    private javax.swing.JLabel lbl_categorie4;
    private javax.swing.JLabel lbl_categories;
    private javax.swing.JLabel lbl_editeur;
    private javax.swing.JLabel lbl_enPromo;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_newCategorie2;
    private javax.swing.JLabel lbl_newSousCategorie2;
    private javax.swing.JLabel lbl_prix;
    private javax.swing.JLabel lbl_prixReduit;
    private javax.swing.JLabel lbl_pwd;
    private javax.swing.JLabel lbl_resume;
    private javax.swing.JLabel lbl_seuil;
    private javax.swing.JLabel lbl_sousCatAff;
    private javax.swing.JLabel lbl_sousCategorie4;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JLabel lbl_titre;
    private javax.swing.JLabel lbl_titreAff1;
    private javax.swing.JMenu m_aPropos;
    private javax.swing.JMenu m_fichier;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_categories;
    private javax.swing.JMenuItem mi_charger;
    private javax.swing.JMenuItem mi_clients;
    private javax.swing.JMenuItem mi_promotions;
    private javax.swing.JMenuItem mi_quitter;
    private javax.swing.JMenuItem mi_sauvegarder;
    private javax.swing.JPanel panGestionCategorie;
    private javax.swing.JPanel pan_affichage;
    private javax.swing.JPanel pan_categories;
    private javax.swing.JPanel pan_clients;
    private javax.swing.JPanel pan_modif;
    private javax.swing.JPanel pan_produits;
    private javax.swing.JPanel pan_promotions;
    private javax.swing.JPanel pan_rechercheProduits;
    private javax.swing.JTextField tf_anneeEditionAff;
    private javax.swing.JTextField tf_auteurAff;
    private javax.swing.JTextField tf_editeurAff;
    private javax.swing.JTextField tf_enPromo;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_login;
    private javax.swing.JTextField tf_newCategorie2;
    private javax.swing.JTextField tf_newSousCategorie2;
    private javax.swing.JTextField tf_prix;
    private javax.swing.JTextField tf_prixReduit;
    private javax.swing.JPasswordField tf_pwd;
    private javax.swing.JTextField tf_resume;
    private javax.swing.JTextField tf_seuil;
    private javax.swing.JTextField tf_stock;
    private javax.swing.JTextField tf_titre;
    private javax.swing.JTextField tf_titreAff;
    private javax.swing.JTabbedPane tpan_accueil;
    // End of variables declaration//GEN-END:variables
}
