/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import metier.*;

/**
 *
 * @author pc
 */
public class FenAcceuil extends javax.swing.JFrame {

    /**
     * Creates new form FenAcceuil
     */
    private static List<Produit> lesProduits;

    private ComboBoxModel<String> modeleDesCategories;
    private ComboBoxModel<String> modeleDesSousCategories;
    private List<Produit> lesProduitsTrouves;

    public FenAcceuil() {

        //Recupérer les catégories produit pour definir un model de combobox
        Object[] tabCategories = CategorieProduit.getLesCategoriesProduit().toArray();
        modeleDesCategories = new DefaultComboBoxModel(tabCategories);

        //Tentative de gestion des catégories de la base de donné, ne marche pas
        /*
       Categorie.buffer.addAll(CategorieDAO.getAllCategories());
       SousCategorie.buffer.addAll(SousCategorieDAO.getAllSousCat());
       
       modeleDesCategories = new DefaultComboBoxModel(
               Categorie.buffer.toArray());
         */
        // implémentation avec Master / Detail
        modeleDesSousCategories = new DefaultComboBoxModel<String>();
        lesProduitsTrouves = new ArrayList<>();

        initComponents();
        // ClientDAO.init(table_client);

        //On récupère dans la liste des produits les produits existants
        lesProduits = Produit.getListeDesProduits();
        Collections.sort(lesProduits);

    }

    //méthode qui résoud l'erreur null
    double ParseDouble(String strNumber) {
        if (strNumber.isEmpty()) {
            return 0.00;
        } else {
            return Double.parseDouble(strNumber);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpan_accueil = new javax.swing.JTabbedPane();
        pan_produits = new javax.swing.JPanel();
        pan_rechercheProduits = new javax.swing.JPanel();
        lbl_titre = new javax.swing.JLabel();
        lbl_categories = new javax.swing.JLabel();
        cb_categories = new javax.swing.JComboBox<>();
        cb_sousCategories = new javax.swing.JComboBox<>();
        tf_titre = new javax.swing.JTextField();
        btn_effacer = new javax.swing.JButton();
        btn_rechercher = new javax.swing.JButton();
        pan_affichage = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        lbl_sousCatAff = new javax.swing.JLabel();
        lbl_editeur = new javax.swing.JLabel();
        lbl_catAff = new javax.swing.JLabel();
        cb_categoriesAff = new javax.swing.JComboBox<>();
        cb_sousCategoriesAff = new javax.swing.JComboBox<>();
        tf_id = new javax.swing.JTextField();
        tf_titreAff = new javax.swing.JTextField();
        lbl_titreAff1 = new javax.swing.JLabel();
        lbl_auteur = new javax.swing.JLabel();
        lbl_anneEdition = new javax.swing.JLabel();
        tf_editeurAff = new javax.swing.JTextField();
        tf_auteurAff = new javax.swing.JTextField();
        tf_anneeEditionAff = new javax.swing.JTextField();
        pan_modif = new javax.swing.JPanel();
        lbl_resume = new javax.swing.JLabel();
        lbl_prix = new javax.swing.JLabel();
        lbl_enPromo = new javax.swing.JLabel();
        lbl_prixReduit = new javax.swing.JLabel();
        lbl_seuil = new javax.swing.JLabel();
        tf_resume = new javax.swing.JTextField();
        tf_prixReduit = new javax.swing.JTextField();
        tf_prix = new javax.swing.JTextField();
        tf_seuil = new javax.swing.JTextField();
        lbl_stock = new javax.swing.JLabel();
        tf_stock = new javax.swing.JTextField();
        cb_enPromo = new javax.swing.JCheckBox();
        btn_ajouter = new javax.swing.JButton();
        btn_modif = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_modif1 = new javax.swing.JButton();
        pan_categories = new javax.swing.JPanel();
        panGestionCategorie = new javax.swing.JPanel();
        lbl_categorie4 = new javax.swing.JLabel();
        lbl_sousCategorie4 = new javax.swing.JLabel();
        lbl_newCategorie2 = new javax.swing.JLabel();
        tf_newCategorie2 = new javax.swing.JTextField();
        cbb_categorieGestion = new javax.swing.JComboBox<>();
        cbb_sousCategorieGestion = new javax.swing.JComboBox<>();
        bt_supprimerCategorie2 = new javax.swing.JButton();
        bt_ajouterSousCatégorie2 = new javax.swing.JButton();
        lbl_newSousCategorie2 = new javax.swing.JLabel();
        tf_newSousCategorie2 = new javax.swing.JTextField();
        bt_ajouterCatégorie2 = new javax.swing.JButton();
        bt_supprimerSousCategorie2 = new javax.swing.JButton();
        bt_cate_valider = new javax.swing.JButton();
        pan_promotions = new javax.swing.JPanel();
        pan_clients = new javax.swing.JPanel();
        pan_rechercheProduits1 = new javax.swing.JPanel();
        lbl_nomClient = new javax.swing.JLabel();
        lbl_prenomClient = new javax.swing.JLabel();
        tf_nomClient = new javax.swing.JTextField();
        btn_ajouterClient = new javax.swing.JButton();
        tf_prenomClient = new javax.swing.JTextField();
        lbl_mdpClient = new javax.swing.JLabel();
        lbl_mailClient = new javax.swing.JLabel();
        tf_mdpClient = new javax.swing.JTextField();
        tf_mailClient = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_client = new javax.swing.JTable();
        btn_supprimerClient = new javax.swing.JButton();
        btn_modifierClient = new javax.swing.JButton();
        btn_enregistrerClient = new javax.swing.JButton();
        mb_menu = new javax.swing.JMenuBar();
        m_fichier = new javax.swing.JMenu();
        mi_produits = new javax.swing.JMenuItem();
        mi_categories = new javax.swing.JMenuItem();
        mi_promotions = new javax.swing.JMenuItem();
        mi_clients = new javax.swing.JMenuItem();
        mi_charger = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mi_sauvegarder = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mi_quitter = new javax.swing.JMenuItem();
        m_aPropos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JIYU - Application de gestion de stock");

        pan_produits.setPreferredSize(new java.awt.Dimension(1200, 7));

        pan_rechercheProduits.setBorder(javax.swing.BorderFactory.createTitledBorder("Rechercher un produit"));

        lbl_titre.setText("Titre :");

        lbl_categories.setText("Catégories :");

        cb_categories.setModel(modeleDesCategories);
        cb_categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoriesActionPerformed(evt);
            }
        });

        cb_sousCategories.setModel(modeleDesSousCategories);
        cb_sousCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sousCategoriesActionPerformed(evt);
            }
        });

        btn_effacer.setText("Effacer");
        btn_effacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_effacerMouseClicked(evt);
            }
        });
        btn_effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_effacerActionPerformed(evt);
            }
        });

        btn_rechercher.setText("Rechercher");
        btn_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_rechercheProduitsLayout = new javax.swing.GroupLayout(pan_rechercheProduits);
        pan_rechercheProduits.setLayout(pan_rechercheProduitsLayout);
        pan_rechercheProduitsLayout.setHorizontalGroup(
            pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_rechercheProduitsLayout.createSequentialGroup()
                .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_rechercheProduitsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_effacer)
                        .addGap(18, 18, 18)
                        .addComponent(btn_rechercher))
                    .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pan_rechercheProduitsLayout.createSequentialGroup()
                            .addComponent(lbl_categories, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_categories, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(cb_sousCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pan_rechercheProduitsLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(lbl_titre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pan_rechercheProduitsLayout.setVerticalGroup(
            pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_rechercheProduitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titre)
                    .addComponent(tf_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_categories)
                    .addComponent(cb_categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_sousCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_rechercheProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_effacer)
                    .addComponent(btn_rechercher)))
        );

        pan_affichage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pan_affichage.setPreferredSize(new java.awt.Dimension(1088, 99));

        lbl_id.setText("ID :");

        lbl_sousCatAff.setText("Sous-catégorie :");

        lbl_editeur.setText("Editeur :");

        lbl_catAff.setText("Catégorie :");

        cb_categoriesAff.setModel(modeleDesCategories);
        cb_categoriesAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoriesAffActionPerformed(evt);
            }
        });

        cb_sousCategoriesAff.setModel(modeleDesSousCategories);
        cb_sousCategoriesAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sousCategoriesAffActionPerformed(evt);
            }
        });

        tf_id.setEditable(false);
        tf_id.setBackground(new java.awt.Color(204, 204, 204));
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        tf_titreAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_titreAffActionPerformed(evt);
            }
        });

        lbl_titreAff1.setText("Titre :");

        lbl_auteur.setText("Auteur :");

        lbl_anneEdition.setText("Année edition :");

        tf_editeurAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_editeurAffActionPerformed(evt);
            }
        });

        tf_auteurAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_auteurAffActionPerformed(evt);
            }
        });

        tf_anneeEditionAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_anneeEditionAffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_affichageLayout = new javax.swing.GroupLayout(pan_affichage);
        pan_affichage.setLayout(pan_affichageLayout);
        pan_affichageLayout.setHorizontalGroup(
            pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_affichageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_id)
                    .addComponent(lbl_titreAff1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_affichageLayout.createSequentialGroup()
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_catAff, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_titreAff, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_affichageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_categoriesAff, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(lbl_sousCatAff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_sousCategoriesAff, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(pan_affichageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_auteurAff, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_editeur, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_editeurAff, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_anneEdition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_anneeEditionAff, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        pan_affichageLayout.setVerticalGroup(
            pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_affichageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id)
                    .addComponent(lbl_catAff)
                    .addComponent(cb_categoriesAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sousCatAff)
                    .addComponent(cb_sousCategoriesAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titreAff1)
                    .addComponent(tf_titreAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_auteur)
                    .addComponent(tf_auteurAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_editeur)
                    .addComponent(tf_editeurAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_anneeEditionAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_anneEdition))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_modif.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pan_modif.setPreferredSize(new java.awt.Dimension(1088, 251));

        lbl_resume.setText("Résumé :");

        lbl_prix.setText("Prix :");

        lbl_enPromo.setText("En promotion ? :");

        lbl_prixReduit.setText("Prix réduit :");

        lbl_seuil.setText("Seuil alerte :");

        tf_prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_prixActionPerformed(evt);
            }
        });

        lbl_stock.setText("Quantité en stock :");

        cb_enPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_enPromoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_modifLayout = new javax.swing.GroupLayout(pan_modif);
        pan_modif.setLayout(pan_modifLayout);
        pan_modifLayout.setHorizontalGroup(
            pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_modifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_resume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_modifLayout.createSequentialGroup()
                        .addComponent(lbl_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_prixReduit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_prixReduit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_enPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_enPromo)
                        .addGap(34, 34, 34)
                        .addComponent(lbl_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_seuil, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_seuil, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_resume, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE))
                .addContainerGap())
        );
        pan_modifLayout.setVerticalGroup(
            pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_modifLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_resume, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_resume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_seuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_enPromo)
                    .addGroup(pan_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_prix)
                        .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_enPromo)
                        .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_stock)
                        .addComponent(tf_prixReduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_prixReduit)
                        .addComponent(lbl_seuil)))
                .addContainerGap())
        );

        btn_ajouter.setText("Ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });

        btn_modif.setText("Modifier");
        btn_modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifActionPerformed(evt);
            }
        });

        btn_supprimer.setText("Supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_modif1.setBackground(new java.awt.Color(255, 204, 204));
        btn_modif1.setText("Suivant");
        btn_modif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modif1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_produitsLayout = new javax.swing.GroupLayout(pan_produits);
        pan_produits.setLayout(pan_produitsLayout);
        pan_produitsLayout.setHorizontalGroup(
            pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_produitsLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(pan_rechercheProduits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pan_produitsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_produitsLayout.createSequentialGroup()
                        .addComponent(btn_supprimer)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btn_modif1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pan_modif, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
                        .addComponent(pan_affichage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_produitsLayout.setVerticalGroup(
            pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_produitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pan_rechercheProduits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_affichage, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pan_modif, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_supprimer)
                    .addComponent(btn_ajouter)
                    .addComponent(btn_modif)
                    .addComponent(btn_modif1))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        tpan_accueil.addTab("Produits", pan_produits);

        panGestionCategorie.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion des Catégories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 10))); // NOI18N

        lbl_categorie4.setText("Liste des catégories");

        lbl_sousCategorie4.setText("Sous-catégories associées");

        lbl_newCategorie2.setText("Nouvelle Catégorie :");

        cbb_categorieGestion.setModel(modeleDesCategories);
        cbb_categorieGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_categorieGestionActionPerformed(evt);
            }
        });

        cbb_sousCategorieGestion.setModel(modeleDesSousCategories);

        bt_supprimerCategorie2.setText("Supprimer la catégorie");
        bt_supprimerCategorie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimerCategorie2ActionPerformed(evt);
            }
        });

        bt_ajouterSousCatégorie2.setText("Ajouter la sous-catégorie");

        lbl_newSousCategorie2.setText("Nouvelle Sous-Catégorie :");

        bt_ajouterCatégorie2.setText("Ajouter la catégorie");
        bt_ajouterCatégorie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ajouterCatégorie2ActionPerformed(evt);
            }
        });

        bt_supprimerSousCategorie2.setText("Supprimer la sous-catégorie");
        bt_supprimerSousCategorie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimerSousCategorie2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panGestionCategorieLayout = new javax.swing.GroupLayout(panGestionCategorie);
        panGestionCategorie.setLayout(panGestionCategorieLayout);
        panGestionCategorieLayout.setHorizontalGroup(
            panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGestionCategorieLayout.createSequentialGroup()
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panGestionCategorieLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lbl_newCategorie2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_newCategorie2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panGestionCategorieLayout.createSequentialGroup()
                            .addComponent(lbl_categorie4)
                            .addGap(1, 1, 1)
                            .addComponent(cbb_categorieGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panGestionCategorieLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_ajouterCatégorie2)
                            .addComponent(bt_supprimerCategorie2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panGestionCategorieLayout.createSequentialGroup()
                            .addComponent(lbl_newSousCategorie2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_newSousCategorie2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panGestionCategorieLayout.createSequentialGroup()
                            .addComponent(lbl_sousCategorie4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbb_sousCategorieGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_ajouterSousCatégorie2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_supprimerSousCategorie2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panGestionCategorieLayout.setVerticalGroup(
            panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGestionCategorieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_categorie4)
                    .addComponent(cbb_categorieGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_sousCategorieGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sousCategorie4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_supprimerCategorie2)
                    .addComponent(bt_supprimerSousCategorie2))
                .addGap(18, 18, 18)
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_newSousCategorie2)
                    .addComponent(tf_newSousCategorie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_newCategorie2)
                    .addComponent(tf_newCategorie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panGestionCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ajouterSousCatégorie2)
                    .addComponent(bt_ajouterCatégorie2))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        bt_cate_valider.setText("Valider");
        bt_cate_valider.setToolTipText("Sauvegarder les données sur les catégories");
        bt_cate_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cate_validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_categoriesLayout = new javax.swing.GroupLayout(pan_categories);
        pan_categories.setLayout(pan_categoriesLayout);
        pan_categoriesLayout.setHorizontalGroup(
            pan_categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_categoriesLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(panGestionCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_categoriesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_cate_valider)
                .addGap(229, 229, 229))
        );
        pan_categoriesLayout.setVerticalGroup(
            pan_categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_categoriesLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(panGestionCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_cate_valider)
                .addContainerGap(424, Short.MAX_VALUE))
        );

        tpan_accueil.addTab("Catégories", pan_categories);

        javax.swing.GroupLayout pan_promotionsLayout = new javax.swing.GroupLayout(pan_promotions);
        pan_promotions.setLayout(pan_promotionsLayout);
        pan_promotionsLayout.setHorizontalGroup(
            pan_promotionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        pan_promotionsLayout.setVerticalGroup(
            pan_promotionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );

        tpan_accueil.addTab("Promotions", pan_promotions);

        pan_rechercheProduits1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations client"));

        lbl_nomClient.setText("Nom :");

        lbl_prenomClient.setText("Prénom :");

        btn_ajouterClient.setText("Ajouter");
        btn_ajouterClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ajouterClientMouseClicked(evt);
            }
        });
        btn_ajouterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterClientActionPerformed(evt);
            }
        });

        lbl_mdpClient.setText("mdp :");

        lbl_mailClient.setText("e-mail :");

        javax.swing.GroupLayout pan_rechercheProduits1Layout = new javax.swing.GroupLayout(pan_rechercheProduits1);
        pan_rechercheProduits1.setLayout(pan_rechercheProduits1Layout);
        pan_rechercheProduits1Layout.setHorizontalGroup(
            pan_rechercheProduits1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_rechercheProduits1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pan_rechercheProduits1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_rechercheProduits1Layout.createSequentialGroup()
                        .addComponent(lbl_nomClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_rechercheProduits1Layout.createSequentialGroup()
                        .addComponent(lbl_mailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_mailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pan_rechercheProduits1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_rechercheProduits1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_prenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_rechercheProduits1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_mdpClient)
                        .addGap(14, 14, 14)))
                .addGroup(pan_rechercheProduits1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_prenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pan_rechercheProduits1Layout.createSequentialGroup()
                        .addComponent(tf_mdpClient, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btn_ajouterClient)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pan_rechercheProduits1Layout.setVerticalGroup(
            pan_rechercheProduits1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_rechercheProduits1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_rechercheProduits1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomClient)
                    .addComponent(tf_nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_prenomClient)
                    .addComponent(tf_prenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pan_rechercheProduits1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_rechercheProduits1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pan_rechercheProduits1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_mailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_mailClient)
                            .addComponent(tf_mdpClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_mdpClient)))
                    .addGroup(pan_rechercheProduits1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btn_ajouterClient)))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        table_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "e-mail", "mdp"
            }
        ));
        table_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_clientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_client);

        btn_supprimerClient.setText("Supprimer");
        btn_supprimerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerClientActionPerformed(evt);
            }
        });

        btn_modifierClient.setText("Modifier");
        btn_modifierClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierClientActionPerformed(evt);
            }
        });

        btn_enregistrerClient.setText("Enregistrer");
        btn_enregistrerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_clientsLayout = new javax.swing.GroupLayout(pan_clients);
        pan_clients.setLayout(pan_clientsLayout);
        pan_clientsLayout.setHorizontalGroup(
            pan_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_clientsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_modifierClient)
                .addGap(61, 61, 61)
                .addComponent(btn_supprimerClient)
                .addGap(64, 64, 64)
                .addComponent(btn_enregistrerClient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(pan_clientsLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(pan_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pan_rechercheProduits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        pan_clientsLayout.setVerticalGroup(
            pan_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_clientsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pan_rechercheProduits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(pan_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_supprimerClient)
                    .addComponent(btn_modifierClient)
                    .addComponent(btn_enregistrerClient))
                .addGap(131, 131, 131))
        );

        tpan_accueil.addTab("Clients", pan_clients);

        getContentPane().add(tpan_accueil, java.awt.BorderLayout.PAGE_START);

        m_fichier.setText("Fichier");
        m_fichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_fichierActionPerformed(evt);
            }
        });

        mi_produits.setText("Gestion Produits");
        mi_produits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_produitsMouseClicked(evt);
            }
        });
        mi_produits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_produitsActionPerformed(evt);
            }
        });
        m_fichier.add(mi_produits);

        mi_categories.setText("Gestion Catégories");
        mi_categories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_categoriesMouseClicked(evt);
            }
        });
        mi_categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_categoriesActionPerformed(evt);
            }
        });
        m_fichier.add(mi_categories);

        mi_promotions.setText("Gestion Promotions");
        mi_promotions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_promotionsMouseClicked(evt);
            }
        });
        mi_promotions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_promotionsActionPerformed(evt);
            }
        });
        m_fichier.add(mi_promotions);

        mi_clients.setText("Gestion Clients");
        mi_clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_clientsMouseClicked(evt);
            }
        });
        mi_clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_clientsActionPerformed(evt);
            }
        });
        m_fichier.add(mi_clients);

        mi_charger.setText("Charger");
        mi_charger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_chargerActionPerformed(evt);
            }
        });
        m_fichier.add(mi_charger);
        m_fichier.add(jSeparator1);

        mi_sauvegarder.setText("Sauvegarder");
        mi_sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_sauvegarderActionPerformed(evt);
            }
        });
        m_fichier.add(mi_sauvegarder);
        m_fichier.add(jSeparator2);

        mi_quitter.setText("Quitter");
        mi_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_quitterActionPerformed(evt);
            }
        });
        m_fichier.add(mi_quitter);

        mb_menu.add(m_fichier);

        m_aPropos.setText("A propos");

        jMenuItem1.setText("Version");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        m_aPropos.add(jMenuItem1);

        mb_menu.add(m_aPropos);

        setJMenuBar(mb_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void affecterDetailCBBox(String ch, JComboBox cbb) {
        // cette méthode affecte la bonne liste de sous-catégories à la CBBox
        Object[] tabCategories;
        boolean flagErreurSousCategorie = false;

        CategorieProduit cat = CategorieProduit.getCategorieFromString(ch);

        switch (cat) {
            case L:
                tabCategories = SousCategorieLitterature.getLesSousCategoriesLitterature().toArray();//select nom_sous_cat from sous_categorie
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                // cbBoxSousCategorieModele = new DefaultComboBoxModel(SousCategorieAccessoires.values());
                // (renvoie les VALEURS de l'énumeration)
                break;
            case J:
                tabCategories = SousCategorieJeunesse.getLesSousCategoriesJeunesse().toArray();
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                break;
            case B:
                tabCategories = SousCategorieBDEtManga.getLesSousCategoriesBDEtManga().toArray();
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                break;
            case A:
                tabCategories = SousCategorieArtEtCulture.getLesSousCategoriesArtEtCulture().toArray();
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                break;
            default:
                flagErreurSousCategorie = true;
                tabCategories = new Object[]{"", "", "", ""};
                modeleDesSousCategories = new DefaultComboBoxModel(tabCategories);
                break;
        }
        cbb.setModel(modeleDesSousCategories);

        if (!flagErreurSousCategorie) {
            cbb.setVisible(true);
        } else {
            cbb.setVisible(false);
        }
    }

    private void mi_categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_categoriesActionPerformed
        // TODO add your handling code here:
        tpan_accueil.setSelectedComponent(pan_categories);
    }//GEN-LAST:event_mi_categoriesActionPerformed

    private void mi_clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_clientsActionPerformed
        // TODO add your handling code here:
        tpan_accueil.setSelectedComponent(pan_clients);
    }//GEN-LAST:event_mi_clientsActionPerformed

    private void mi_sauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_sauvegarderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_sauvegarderActionPerformed

    private void mi_promotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_promotionsActionPerformed
        // TODO add your handling code here:
        tpan_accueil.setSelectedComponent(pan_promotions);
    }//GEN-LAST:event_mi_promotionsActionPerformed

    private void mi_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_quitterActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment quitter ?", "Attention", JOptionPane.OK_CANCEL_OPTION);
        if (reply == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mi_quitterActionPerformed

    private void mi_chargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_chargerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_chargerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Application réalisée par Romane BERTHE et Marie MICHEL - Version 1",
                "A propos...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mi_categoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_categoriesMouseClicked


    }//GEN-LAST:event_mi_categoriesMouseClicked

    private void mi_promotionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_promotionsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_promotionsMouseClicked

    private void mi_clientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_clientsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_clientsMouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void m_fichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_fichierActionPerformed
        // TODO add your handling code here:
        tpan_accueil.setSelectedComponent(pan_categories);
    }//GEN-LAST:event_m_fichierActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        // suppression d'un produit dans la base de donnée:
        if (tf_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez selectionner un produit à supprimer.");
        } else {
            Produit test = new Produit(Integer.valueOf(tf_id.getText()));
            ProduitDAO.supprimerProduit(test);

        }
    }//GEN-LAST:event_btn_supprimerActionPerformed
//Ne marche plus
    private void btn_modifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifActionPerformed
        // Modifier un produit (ne modifie pas les id catégorie et sous-catégorie):
        if (tf_titreAff.getText().isEmpty() || tf_auteurAff.getText().isEmpty() || tf_editeurAff.getText().isEmpty() || tf_anneeEditionAff.getText().isEmpty() || tf_resume.getText().isEmpty() || tf_prix.getText().isEmpty() || tf_stock.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Il manque des informations.");

        } else {

            String titre = tf_titreAff.getText();
            Double prix = Double.parseDouble(tf_prix.getText());
            String description = tf_resume.getText();
            String auteur = tf_auteurAff.getText();
            String editeur = tf_editeurAff.getText();
            int annee = Integer.parseInt(tf_anneeEditionAff.getText());
            Double prixReduit = Double.parseDouble(tf_prixReduit.getText());
            int quantite = Integer.parseInt(tf_stock.getText());
            boolean enstock = true;
            int seuil = Integer.parseInt(tf_seuil.getText());

            if (Integer.valueOf(tf_stock.getText()) < 0) {
                enstock = false;
            }

            String cat = cb_categoriesAff.getSelectedItem().toString();
            int idCat = CategorieProduitDAO.findIdCategorieProduit((String) cat);

            int idSousCat = SousCategorieProduitDAO.findIdSousCategorieProduitByIdCat(idCat);

            Produit testid = new Produit(titre, prix, description, auteur, editeur, annee, prixReduit, quantite, enstock, seuil, idCat, idSousCat, false);

            /*String update ="UPDATE produit p SET titre=?,prix=?, resumé=?, auteur=?, editeur=?, "
                    + "anne_edition=?, prix_reduit=?, stock=?, "
                    + "seuil=?, en_promotion=? WHERE id_produit='" + tf_id.getText()+"'";
           try{ 
               conn = DriverManager.getConnection(HOST, USERNAME, PASSWORD);
               
               PreparedStatement st = conn.prepareStatement(update);
           st.setString(1, titre);

            st.setDouble(2, prix);
            st.setString(3, description);
            st.setString(4, auteur);
            st.setString(5, editeur);
            st.setInt(6, annee);
            st.setDouble(7, prixReduit);
            st.setInt(8, quantite);
            st.setInt(9,seuil);
            st.setBoolean(10, false);
            
            st.execute();
           }catch(SQLException e){
               e.printStackTrace();
               
           }*/
            ProduitDAO.updateProduit(testid);

        }
    }//GEN-LAST:event_btn_modifActionPerformed

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // Ajoute un produit à la base de données: 

        String titre = tf_titreAff.getText();
        double prix = Double.parseDouble(tf_prix.getText());
        String description = tf_resume.getText();
        String auteur = tf_auteurAff.getText();
        String editeur = tf_editeurAff.getText();
        int annee = Integer.parseInt(tf_anneeEditionAff.getText());
        double prixReduit = Double.parseDouble(tf_prixReduit.getText());
        int quantite = Integer.parseInt(tf_stock.getText());
        boolean enstock = true;
        int seuil = Integer.parseInt(tf_seuil.getText());

        if (Integer.valueOf(tf_stock.getText()) < 0) {
            enstock = false;
        }

        //Tentatove d'implémentation de la bdd, ne marche pas
        /*
        Categorie cat = (Categorie) cb_categoriesAff.getSelectedItem();
        int idCat = cat.getID();
        int idCat = CategorieDAO.findIdCategorieProduit(cat.toString());
        
        SousCategorie souscat = (SousCategorie)cb_sousCategoriesAff.getSelectedItem();
        
       
        SousCategorie.buffer.addAll(SousCategorieDAO.getAllSousCat());
        int idSousCat = souscat.getID();
         */
        String cat = cb_categoriesAff.getSelectedItem().toString();
        int idCat = CategorieProduitDAO.findIdCategorieProduit((String) cat);
        int idSousCat = SousCategorieProduitDAO.findIdSousCategorieProduitByIdCat(idCat);
        
        boolean isenpromo = cb_enPromo.isSelected();
        
        

        Produit testid = new Produit(titre, prix, description, auteur, editeur, annee, prixReduit, quantite, enstock, seuil, idCat, idSousCat, isenpromo);
        ProduitDAO.insertProduit(testid);
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void tf_anneeEditionAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_anneeEditionAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_anneeEditionAffActionPerformed

    private void tf_auteurAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_auteurAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_auteurAffActionPerformed

    private void tf_editeurAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_editeurAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_editeurAffActionPerformed

    private void tf_titreAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_titreAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_titreAffActionPerformed

    private void tf_prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_prixActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_tf_idActionPerformed

    private void cb_categoriesAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoriesAffActionPerformed
        // TODO add your handling code here:
        String laCategorie = (String) cb_categoriesAff.getSelectedItem();
        this.affecterDetailCBBox(laCategorie, cb_sousCategoriesAff);


    }//GEN-LAST:event_cb_categoriesAffActionPerformed

    private void cbb_categorieGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_categorieGestionActionPerformed
        //Gère l'affichage des combobox sous-catégorie en fonction des catégories (pas connecté avec la bdd)

        String laCategorie = (String) cbb_categorieGestion.getSelectedItem();
        this.affecterDetailCBBox(laCategorie, cbb_sousCategorieGestion);

    }//GEN-LAST:event_cbb_categorieGestionActionPerformed

    private void bt_supprimerCategorie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimerCategorie2ActionPerformed
        // attention : on ne pourra supprimer la catégorie que s'il n'y a plus
        // aucun produit de cette catégorie
        // idée : afficher la liste des produits concernés
        //Ne vérifie pas si la liste des produits est vide
        //if (lesProduits.isEmpty()){
        String cat = cbb_categorieGestion.getSelectedItem().toString();
        CategorieProduitDAO.supprimerCategorie(cat);
        // }

    }//GEN-LAST:event_bt_supprimerCategorie2ActionPerformed

    private void bt_cate_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cate_validerActionPerformed
        // sauvegarder les catégories et sous-catégories avec les modifs effectuées
    }//GEN-LAST:event_bt_cate_validerActionPerformed

    private void btn_modif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modif1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modif1ActionPerformed

    private void btn_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rechercherActionPerformed
        // TODO add your handling code here:
        //rajouter un message si le produit recherché n'existe pas 

        Produit result = ProduitDAO.RechercheProduitByTitre(tf_titre.getText());
        tf_id.setText(String.valueOf(result.getId()));
        tf_titreAff.setText(result.getTitre());
        tf_prix.setText(String.valueOf(result.getPrix()));
        tf_resume.setText(result.getDescription());
        tf_auteurAff.setText(result.getAuteur());
        tf_editeurAff.setText(result.getEditeur());
        tf_anneeEditionAff.setText(String.valueOf(result.getAnnee()));
        tf_prixReduit.setText(String.valueOf(result.getRemise()));
        tf_stock.setText(String.valueOf(result.getQuantite()));
        tf_seuil.setText(String.valueOf(result.getSeuil()));
        cb_categoriesAff.setSelectedIndex(result.getIdCat());
        cb_sousCategoriesAff.setSelectedItem(result.getSousCategorie()); //a trouver
        cb_enPromo.setSelected(result.isEnPromo());
        



    }//GEN-LAST:event_btn_rechercherActionPerformed

    private void btn_effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_effacerActionPerformed
        // TODO add your handling code here:
        tf_titre.setText("");
        cb_categories.setSelectedIndex(0);
        cb_sousCategories.setSelectedIndex(0);
        tf_id.setText("");
        tf_titreAff.setText("");
        tf_auteurAff.setText("");
        tf_editeurAff.setText("");
        tf_anneeEditionAff.setText("");
        tf_resume.setText("");
        tf_prix.setText("");
        tf_prixReduit.setText("");
        cb_enPromo.setText("");
        tf_seuil.setText("");
        tf_stock.setText("");
    }//GEN-LAST:event_btn_effacerActionPerformed

    private void btn_effacerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_effacerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_effacerMouseClicked

    private void cb_sousCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sousCategoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_sousCategoriesActionPerformed

    private void cb_categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoriesActionPerformed
        // TODO add your handling code here:
        // on définit le contenu de la comboBox des sous categories en
        // fonction de l'item selectionné

        String laCategorie = (String) cb_categories.getSelectedItem(); // getSelectedItem() renvoie un Object par defaut
        this.affecterDetailCBBox(laCategorie, cb_sousCategories);

    }//GEN-LAST:event_cb_categoriesActionPerformed

    private void cb_enPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_enPromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_enPromoActionPerformed

    private void btn_supprimerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_supprimerClientActionPerformed

    private void btn_ajouterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ajouterClientActionPerformed

    private void btn_ajouterClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajouterClientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ajouterClientMouseClicked

    private void btn_modifierClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modifierClientActionPerformed

    private void btn_enregistrerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_enregistrerClientActionPerformed

    private void table_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_clientMouseClicked
        // TODO add your handling code here:
        /* DefaultTableModel model = (DefaultTableModel)table_client.getModel();
        int monIndex = table_client.getSelectedRow();
        tf_nomClient.setText(model.getValueAt(monIndex, 0).toString());
        tf_prenomClient.setText(model.getValueAt(monIndex, 1).toString());
        tf_mailClient.setText(model.getValueAt(monIndex, 2).toString());
        tf_mdpClient.setText(model.getValueAt(monIndex, 3).toString());*/

    }//GEN-LAST:event_table_clientMouseClicked

    private void mi_produitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_produitsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_produitsMouseClicked

    private void mi_produitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_produitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_produitsActionPerformed

    private void cb_sousCategoriesAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sousCategoriesAffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_sousCategoriesAffActionPerformed

    private void bt_supprimerSousCategorie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimerSousCategorie2ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_bt_supprimerSousCategorie2ActionPerformed

    private void bt_ajouterCatégorie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ajouterCatégorie2ActionPerformed
        // TODO add your handling code here:
        String cat = tf_newCategorie2.getText();
        CategorieProduitDAO.insertCategorieProduit(cat);

    }//GEN-LAST:event_bt_ajouterCatégorie2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ajouterCatégorie2;
    private javax.swing.JButton bt_ajouterSousCatégorie2;
    private javax.swing.JButton bt_cate_valider;
    private javax.swing.JButton bt_supprimerCategorie2;
    private javax.swing.JButton bt_supprimerSousCategorie2;
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_ajouterClient;
    private javax.swing.JButton btn_effacer;
    private javax.swing.JButton btn_enregistrerClient;
    private javax.swing.JButton btn_modif;
    private javax.swing.JButton btn_modif1;
    private javax.swing.JButton btn_modifierClient;
    private javax.swing.JButton btn_rechercher;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JButton btn_supprimerClient;
    private javax.swing.JComboBox<String> cb_categories;
    private javax.swing.JComboBox<String> cb_categoriesAff;
    private javax.swing.JCheckBox cb_enPromo;
    private javax.swing.JComboBox<String> cb_sousCategories;
    private javax.swing.JComboBox<String> cb_sousCategoriesAff;
    private javax.swing.JComboBox<String> cbb_categorieGestion;
    private javax.swing.JComboBox<String> cbb_sousCategorieGestion;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbl_anneEdition;
    private javax.swing.JLabel lbl_auteur;
    private javax.swing.JLabel lbl_catAff;
    private javax.swing.JLabel lbl_categorie4;
    private javax.swing.JLabel lbl_categories;
    private javax.swing.JLabel lbl_editeur;
    private javax.swing.JLabel lbl_enPromo;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_mailClient;
    private javax.swing.JLabel lbl_mdpClient;
    private javax.swing.JLabel lbl_newCategorie2;
    private javax.swing.JLabel lbl_newSousCategorie2;
    private javax.swing.JLabel lbl_nomClient;
    private javax.swing.JLabel lbl_prenomClient;
    private javax.swing.JLabel lbl_prix;
    private javax.swing.JLabel lbl_prixReduit;
    private javax.swing.JLabel lbl_resume;
    private javax.swing.JLabel lbl_seuil;
    private javax.swing.JLabel lbl_sousCatAff;
    private javax.swing.JLabel lbl_sousCategorie4;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JLabel lbl_titre;
    private javax.swing.JLabel lbl_titreAff1;
    private javax.swing.JMenu m_aPropos;
    private javax.swing.JMenu m_fichier;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_categories;
    private javax.swing.JMenuItem mi_charger;
    private javax.swing.JMenuItem mi_clients;
    private javax.swing.JMenuItem mi_produits;
    private javax.swing.JMenuItem mi_promotions;
    private javax.swing.JMenuItem mi_quitter;
    private javax.swing.JMenuItem mi_sauvegarder;
    private javax.swing.JPanel panGestionCategorie;
    private javax.swing.JPanel pan_affichage;
    private javax.swing.JPanel pan_categories;
    private javax.swing.JPanel pan_clients;
    private javax.swing.JPanel pan_modif;
    private javax.swing.JPanel pan_produits;
    private javax.swing.JPanel pan_promotions;
    private javax.swing.JPanel pan_rechercheProduits;
    private javax.swing.JPanel pan_rechercheProduits1;
    private javax.swing.JTable table_client;
    private javax.swing.JTextField tf_anneeEditionAff;
    private javax.swing.JTextField tf_auteurAff;
    private javax.swing.JTextField tf_editeurAff;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_mailClient;
    private javax.swing.JTextField tf_mdpClient;
    private javax.swing.JTextField tf_newCategorie2;
    private javax.swing.JTextField tf_newSousCategorie2;
    private javax.swing.JTextField tf_nomClient;
    private javax.swing.JTextField tf_prenomClient;
    private javax.swing.JTextField tf_prix;
    private javax.swing.JTextField tf_prixReduit;
    private javax.swing.JTextField tf_resume;
    private javax.swing.JTextField tf_seuil;
    private javax.swing.JTextField tf_stock;
    private javax.swing.JTextField tf_titre;
    private javax.swing.JTextField tf_titreAff;
    private javax.swing.JTabbedPane tpan_accueil;
    // End of variables declaration//GEN-END:variables
}
